### ISSUE TITLE
Stable release?

### ISSUE THREAD

**Issue by conao3** [alphapapa/bashcaster#4]
Thanks for such a useful tool!
It hasn't been updated in two years (this isn't to point out that it hasn't been maintained) and I think the software is stable enough.
Please consider tagging any commit to indicate stable release?

**Comment by alphapapa** [comment]
Sure, why not.  I tagged the latest as 0.1.

Curious, is there something you expect to make use of that tag?

**Comment by conao3** [comment]
Thanks. I want to create `bashcaster` Arch AUR PKGBUILD file based the tag release commit.
